global ROUND_NUMBER
ROUND_NUMBER = 1

# For N levels of tournament brackets fights, use 2 ** N for FIGHTER_COUNT
FIGHTER_COUNT = 2 ** 5
MAX_FIGHT_MOMENTS = 300
DAMAGE_MULTIPLIER = 3
DEFAULT_COOLDOWN = 20
DODGE_THRESHOLD = 0.9